name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
          echo "AWS key ${{ secrets.AWS_ACCESS_KEY }}"
          echo "AWS secret ${{ secrets.AWS_SECRET_KEY }}"
          # Add similar lines for other secrets
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t grantcthomas/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true grantcthomas/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: crafrontend
          environment_name: Crafrontend-env
          existing_bucket_name: ${{ secrets.S3_BUCKET }}
          region: us-west-1
          version_label: 12345
          deployment_package: deploy.zip
